---
abstract: 'Never install pure Perl modules again'
author:
  - 'Nicholas R. Perez <nperez@cpan.org>'
build_requires:
  Number::Zero: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300014, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CloudPAN
requires:
  File::Path: 0
  File::Spec: 0
  File::Temp: 0
  HTTP::Tiny: 0.022
  MetaCPAN::API::Tiny: 0
  Symbol: 0
  strict: 0
  warnings: 0
resources:
  repository: git://github.com/nperez/cloudpan
version: 1.123260
